# Generated by Django 3.2.3 on 2021-06-30 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=200)),
                ('fecha_ciudad', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_cliente', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('ap_paterno', models.CharField(max_length=200)),
                ('ap_materno', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=200)),
                ('numeracion', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=12)),
                ('fecha_cliente', models.DateTimeField(verbose_name='date published')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasteleria.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comuna', models.CharField(max_length=200)),
                ('fecha_comuna', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('ap_paterno_cliente', models.CharField(max_length=200)),
                ('ap_materno_cliente', models.CharField(max_length=200)),
                ('email_cliente', models.CharField(max_length=200)),
                ('celular_cliente', models.CharField(max_length=12)),
                ('direccion_cliente', models.CharField(max_length=200)),
                ('numeracion_clietne', models.IntegerField(default=0)),
                ('numero_tarjeta', models.IntegerField(default=0)),
                ('mes_expiracion', models.IntegerField(default=0)),
                ('anno_exiparacion', models.IntegerField(default=0)),
                ('cvv', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasteleria.producto')),
                ('run_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasteleria.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasteleria.comuna'),
        ),
    ]
