# Generated by Django 3.2.3 on 2021-07-02 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasteleria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': (('comprador', 'Es comprador'),)},
        ),
    ]
